apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "review-agent.fullname" . }}-config
  labels: {{- include "review-agent.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
