{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "review-agent.fullname" . }}
  labels:
    {{- include "review-agent.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "review-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: receiver
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.metricsPath }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
